import type { TransportOption } from "@/types/booking";

export const TRANSPORT_OPTIONS: TransportOption[] = [
  {
    id: "economy",
    label: "Economy",
    description: "Affordable rides for everyday trips",
    seats: 4,
    priceMultiplier: 1,
    etaMinutesOffset: 0,
    icon: "Car",
    driverMode: null,
  },
  {
    id: "premium",
    label: "Premium",
    description: "Comfort and style",
    seats: 4,
    priceMultiplier: 1.5,
    etaMinutesOffset: 2,
    icon: "Car",
    driverMode: null,
  },
  {
    id: "xl",
    label: "XL",
    description: "Extra space for groups",
    seats: 6,
    priceMultiplier: 2,
    etaMinutesOffset: 5,
    icon: "Car",
    driverMode: null,
  },
  {
    id: "self_driver",
    label: "Self Driver",
    description: "Independent driver — instant match",
    seats: 4,
    priceMultiplier: 1,
    etaMinutesOffset: 0,
    icon: "User",
    driverMode: "self",
  },
  {
    id: "company_driver",
    label: "Company Driver",
    description: "Assigned by fleet — fixed pricing",
    seats: 4,
    priceMultiplier: 1.2,
    etaMinutesOffset: 10,
    icon: "Building2",
    driverMode: "company",
  },
];
